import { getDatabase } from './src/database/database.js';

const db = getDatabase();

console.log('🔍 Recherche de tous les mots non traduits...\n');

// D'abord, voyons combien de mots il reste à corriger
const untranslatedWords = db.db.prepare(`
    SELECT word, translation 
    FROM words 
    WHERE translation LIKE '[%]'
    ORDER BY word
`).all();

console.log(`📊 Trouvé ${untranslatedWords.length} mots à corriger\n`);

// Affichons les 50 premiers pour voir quels types de mots il faut corriger
console.log('🔤 Premiers mots à corriger:');
untranslatedWords.slice(0, 50).forEach((row, index) => {
    console.log(`${index + 1}. ${row.word} -> ${row.translation}`);
});

if (untranslatedWords.length > 50) {
    console.log(`... et ${untranslatedWords.length - 50} autres mots`);
}

// Créons un dictionnaire complet pour TOUS les mots courants
const massiveTranslationDict = {
    // Verbes d'action de base
    'abandon': 'abandonner',
    'ability': 'capacité',
    'able': 'capable',
    'abortion': 'avortement',
    'about': 'à propos',
    'above': 'au-dessus',
    'abroad': 'à l\'étranger',
    'absence': 'absence',
    'absolute': 'absolu',
    'absolutely': 'absolument',
    'absorb': 'absorber',
    'abuse': 'abus',
    'academic': 'académique',
    'accept': 'accepter',
    'access': 'accès',
    'accident': 'accident',
    'accompany': 'accompagner',
    'accomplish': 'accomplir',
    'according': 'selon',
    'account': 'compte',
    'accurate': 'précis',
    'accuse': 'accuser',
    'achieve': 'atteindre',
    'achievement': 'réalisation',
    'acid': 'acide',
    'acknowledge': 'reconnaître',
    'acquire': 'acquérir',
    'across': 'à travers',
    'act': 'agir',
    'action': 'action',
    'active': 'actif',
    'activist': 'activiste',
    'activity': 'activité',
    'actor': 'acteur',
    'actress': 'actrice',
    'actual': 'réel',
    'actually': 'en fait',
    'ad': 'publicité',
    'adapt': 'adapter',
    'add': 'ajouter',
    'addition': 'addition',
    'additional': 'supplémentaire',
    'address': 'adresse',
    'adequate': 'adéquat',
    'administration': 'administration',
    'administrative': 'administratif',
    'administrator': 'administrateur',
    'admire': 'admirer',
    'admission': 'admission',
    'admit': 'admettre',
    'adolescent': 'adolescent',
    'adopt': 'adopter',
    'adult': 'adulte',
    'advance': 'avancer',
    'advanced': 'avancé',
    'advantage': 'avantage',
    'adventure': 'aventure',
    'advertising': 'publicité',
    'advice': 'conseil',
    'adviser': 'conseiller',
    'advocate': 'défenseur',
    'affair': 'affaire',
    'affect': 'affecter',
    'afford': 'se permettre',
    'afraid': 'effrayé',
    'african': 'africain',
    'after': 'après',
    'afternoon': 'après-midi',
    'afterwards': 'après',
    'again': 'encore',
    'against': 'contre',
    'age': 'âge',
    'aged': 'âgé',
    'agency': 'agence',
    'agenda': 'agenda',
    'agent': 'agent',
    'aggressive': 'agressif',
    'ago': 'il y a',
    'agree': 'être d\'accord',
    'agreement': 'accord',
    'agricultural': 'agricole',
    'agriculture': 'agriculture',
    'ahead': 'devant',
    'aid': 'aide',
    'aim': 'viser',
    'air': 'air',
    'aircraft': 'aéronef',
    'airline': 'compagnie aérienne',
    'airport': 'aéroport',
    'alarm': 'alarme',
    'album': 'album',
    'alcohol': 'alcool',
    'alert': 'alerte',
    'alien': 'étranger',
    'alive': 'vivant',
    'all': 'tout',
    'alliance': 'alliance',
    'allow': 'permettre',
    'almost': 'presque',
    'alone': 'seul',
    'along': 'le long',
    'alongside': 'aux côtés',
    'already': 'déjà',
    'also': 'aussi',
    'alter': 'modifier',
    'alternative': 'alternative',
    'although': 'bien que',
    'altogether': 'tout à fait',
    'always': 'toujours',
    'amazing': 'incroyable',
    'ambition': 'ambition',
    'ambulance': 'ambulance',
    'american': 'américain',
    'among': 'parmi',
    'amount': 'montant',
    'analysis': 'analyse',
    'analyst': 'analyste',
    'analyze': 'analyser',
    'ancient': 'ancien',
    'anger': 'colère',
    'angle': 'angle',
    'angry': 'en colère',
    'animal': 'animal',
    'anniversary': 'anniversaire',
    'announce': 'annoncer',
    'annual': 'annuel',
    'another': 'autre',
    'answer': 'réponse',
    'anticipate': 'anticiper',
    'anxiety': 'anxiété',
    'anxious': 'anxieux',
    'any': 'tout',
    'anybody': 'n\'importe qui',
    'anymore': 'plus',
    'anyone': 'n\'importe qui',
    'anything': 'n\'importe quoi',
    'anyway': 'de toute façon',
    'anywhere': 'n\'importe où',
    'apart': 'à part',
    'apartment': 'appartement',
    'apparent': 'apparent',
    'apparently': 'apparemment',
    'appeal': 'appel',
    'appear': 'apparaître',
    'appearance': 'apparence',
    'apple': 'pomme',
    'application': 'application',
    'apply': 'appliquer',
    'appoint': 'nommer',
    'appointment': 'rendez-vous',
    'appreciate': 'apprécier',
    'approach': 'approche',
    'appropriate': 'approprié',
    'approval': 'approbation',
    'approve': 'approuver',
    'approximately': 'approximativement',
    'arab': 'arabe',
    'architect': 'architecte',
    'architecture': 'architecture',
    'area': 'zone',
    'argue': 'argumenter',
    'argument': 'argument',
    'arise': 'surgir',
    'arm': 'bras',
    'armed': 'armé',
    'army': 'armée',
    'around': 'autour',
    'arrange': 'organiser',
    'arrangement': 'arrangement',
    'arrest': 'arrestation',
    'arrival': 'arrivée',
    'arrive': 'arriver',
    'art': 'art',
    'article': 'article',
    'artist': 'artiste',
    'artistic': 'artistique',
    'as': 'comme',
    'asian': 'asiatique',
    'aside': 'à côté',
    'ask': 'demander',
    'asleep': 'endormi',
    'aspect': 'aspect',
    'assault': 'agression',
    'assert': 'affirmer',
    'assess': 'évaluer',
    'assessment': 'évaluation',
    'asset': 'actif',
    'assign': 'assigner',
    'assignment': 'affectation',
    'assist': 'aider',
    'assistance': 'assistance',
    'assistant': 'assistant',
    'associate': 'associer',
    'association': 'association',
    'assume': 'supposer',
    'assumption': 'supposition',
    'ensure': 'assurer',
    'at': 'à',
    'athlete': 'athlète',
    'athletic': 'athlétique',
    'atmosphere': 'atmosphère',
    'attach': 'attacher',
    'attack': 'attaque',
    'attempt': 'tentative',
    'attend': 'assister',
    'attention': 'attention',
    'attitude': 'attitude',
    'attorney': 'avocat',
    'attract': 'attirer',
    'attractive': 'attrayant',
    'attribute': 'attribut',
    'audience': 'public',
    'author': 'auteur',
    'authority': 'autorité',
    'auto': 'auto',
    'automatic': 'automatique',
    'automatically': 'automatiquement',
    'automobile': 'automobile',
    'available': 'disponible',
    'average': 'moyenne',
    'avoid': 'éviter',
    'award': 'prix',
    'aware': 'conscient',
    'awareness': 'conscience',
    'away': 'loin',
    'awful': 'affreux',

    // Mots commençant par B
    'baby': 'bébé',
    'back': 'dos',
    'background': 'arrière-plan',
    'backup': 'sauvegarde',
    'bad': 'mauvais',
    'badly': 'mal',
    'bag': 'sac',
    'balance': 'équilibre',
    'ball': 'balle',
    'ban': 'interdire',
    'band': 'groupe',
    'bank': 'banque',
    'bar': 'bar',
    'barely': 'à peine',
    'bargain': 'affaire',
    'barrel': 'baril',
    'barrier': 'barrière',
    'base': 'base',
    'baseball': 'baseball',
    'basic': 'basique',
    'basically': 'essentiellement',
    'basis': 'base',
    'basketball': 'basketball',
    'bathroom': 'salle de bain',
    'battery': 'batterie',
    'battle': 'bataille',
    'be': 'être',
    'beach': 'plage',
    'bean': 'haricot',
    'bear': 'ours',
    'beat': 'battre',
    'beautiful': 'beau',
    'beauty': 'beauté',
    'because': 'parce que',
    'become': 'devenir',
    'bed': 'lit',
    'bedroom': 'chambre',
    'beef': 'bœuf',
    'beer': 'bière',
    'before': 'avant',
    'begin': 'commencer',
    'beginning': 'début',
    'behalf': 'nom',
    'behave': 'se comporter',
    'behavior': 'comportement',
    'behind': 'derrière',
    'being': 'être',
    'belief': 'croyance',
    'believe': 'croire',
    'bell': 'cloche',
    'belong': 'appartenir',
    'below': 'en dessous',
    'belt': 'ceinture',
    'bench': 'banc',
    'bend': 'plier',
    'beneath': 'sous',
    'benefit': 'bénéfice',
    'beside': 'à côté',
    'best': 'meilleur',
    'bet': 'parier',
    'better': 'mieux',
    'between': 'entre',
    'beyond': 'au-delà',
    'bicycle': 'vélo',
    'bid': 'offre',
    'big': 'grand',
    'bike': 'vélo',
    'bill': 'facture',
    'billion': 'milliard',
    'bind': 'lier',
    'biological': 'biologique',
    'bird': 'oiseau',
    'birth': 'naissance',
    'birthday': 'anniversaire',
    'bit': 'peu',
    'bite': 'mordre',
    'black': 'noir',
    'blade': 'lame',
    'blame': 'blâmer',
    'blank': 'vide',
    'blanket': 'couverture',
    'blind': 'aveugle',
    'block': 'bloc',
    'blood': 'sang',
    'blow': 'souffler',
    'blue': 'bleu',
    'board': 'conseil',
    'boat': 'bateau',
    'body': 'corps',
    'bomb': 'bombe',
    'bond': 'lien',
    'bone': 'os',
    'book': 'livre',
    'boom': 'boom',
    'boost': 'stimuler',
    'boot': 'botte',
    'border': 'frontière',
    'born': 'né',
    'borrow': 'emprunter',
    'boss': 'patron',
    'both': 'les deux',
    'bother': 'déranger',
    'bottle': 'bouteille',
    'bottom': 'fond',
    'boundary': 'frontière',
    'bowl': 'bol',
    'box': 'boîte',
    'boy': 'garçon',
    'boyfriend': 'petit ami',
    'brain': 'cerveau',
    'branch': 'branche',
    'brand': 'marque',
    'brave': 'courageux',
    'bread': 'pain',
    'break': 'casser',
    'breakfast': 'petit-déjeuner',
    'breast': 'sein',
    'breath': 'souffle',
    'breathe': 'respirer',
    'breed': 'race',
    'brick': 'brique',
    'bridge': 'pont',
    'brief': 'bref',
    'briefly': 'brièvement',
    'bright': 'brillant',
    'brilliant': 'brillant',
    'bring': 'apporter',
    'broad': 'large',
    'broken': 'cassé',
    'brother': 'frère',
    'brown': 'marron',
    'brush': 'brosse',
    'budget': 'budget',
    'build': 'construire',
    'building': 'bâtiment',
    'bullet': 'balle',
    'bunch': 'groupe',
    'burden': 'fardeau',
    'burn': 'brûler',
    'bury': 'enterrer',
    'bus': 'bus',
    'business': 'entreprise',
    'busy': 'occupé',
    'but': 'mais',
    'butter': 'beurre',
    'button': 'bouton',
    'buy': 'acheter',
    'buyer': 'acheteur',
    'by': 'par',

    // Mots commençant par C
    'cabinet': 'cabinet',
    'cable': 'câble',
    'cake': 'gâteau',
    'calculate': 'calculer',
    'call': 'appeler',
    'camera': 'caméra',
    'camp': 'camp',
    'campaign': 'campagne',
    'campus': 'campus',
    'can': 'pouvoir',
    'cancer': 'cancer',
    'candidate': 'candidat',
    'candy': 'bonbon',
    'cap': 'casquette',
    'capability': 'capacité',
    'capable': 'capable',
    'capacity': 'capacité',
    'capital': 'capital',
    'captain': 'capitaine',
    'capture': 'capturer',
    'car': 'voiture',
    'carbon': 'carbone',
    'card': 'carte',
    'care': 'soin',
    'career': 'carrière',
    'careful': 'prudent',
    'carefully': 'soigneusement',
    'carry': 'porter',
    'case': 'cas',
    'cash': 'argent',
    'cast': 'jeter',
    'cat': 'chat',
    'catch': 'attraper',
    'category': 'catégorie',
    'cause': 'cause',
    'ceiling': 'plafond',
    'celebrate': 'célébrer',
    'celebration': 'célébration',
    'celebrity': 'célébrité',
    'cell': 'cellule',
    'center': 'centre',
    'central': 'central',
    'century': 'siècle',
    'ceremony': 'cérémonie',
    'certain': 'certain',
    'certainly': 'certainement',
    'chain': 'chaîne',
    'chair': 'chaise',
    'chairman': 'président',
    'challenge': 'défi',
    'chamber': 'chambre',
    'champion': 'champion',
    'championship': 'championnat',
    'chance': 'chance',
    'change': 'changer',
    'channel': 'chaîne',
    'chapter': 'chapitre',
    'character': 'caractère',
    'characteristic': 'caractéristique',
    'characterize': 'caractériser',
    'charge': 'charger',
    'charity': 'charité',
    'chart': 'graphique',
    'chase': 'chasser',
    'cheap': 'bon marché',
    'check': 'vérifier',
    'cheek': 'joue',
    'cheese': 'fromage',
    'chemical': 'chimique',
    'chest': 'poitrine',
    'chicken': 'poulet',
    'chief': 'chef',
    'child': 'enfant',
    'childhood': 'enfance',
    'chin': 'menton',
    'chocolate': 'chocolat',
    'choice': 'choix',
    'choose': 'choisir',
    'church': 'église',
    'cigarette': 'cigarette',
    'circle': 'cercle',
    'circumstance': 'circonstance',
    'cite': 'citer',
    'citizen': 'citoyen',
    'city': 'ville',
    'civil': 'civil',
    'civilian': 'civil',
    'claim': 'revendiquer',
    'class': 'classe',
    'classic': 'classique',
    'classroom': 'salle de classe',
    'clean': 'propre',
    'clear': 'clair',
    'clearly': 'clairement',
    'client': 'client',
    'climate': 'climat',
    'climb': 'grimper',
    'clinic': 'clinique',
    'clock': 'horloge',
    'close': 'fermer',
    'closely': 'étroitement',
    'closer': 'plus proche',
    'clothes': 'vêtements',
    'clothing': 'vêtements',
    'cloud': 'nuage',
    'club': 'club',
    'clue': 'indice',
    'coach': 'entraîneur',
    'coal': 'charbon',
    'coast': 'côte',
    'coat': 'manteau',
    'code': 'code',
    'coffee': 'café',
    'coin': 'pièce',
    'cold': 'froid',
    'collapse': 'effondrer',
    'colleague': 'collègue',
    'collect': 'collecter',
    'collection': 'collection',
    'college': 'université',
    'color': 'couleur',
    'column': 'colonne',
    'combination': 'combinaison',
    'combine': 'combiner',
    'come': 'venir',
    'comedy': 'comédie',
    'comfort': 'confort',
    'comfortable': 'confortable',
    'command': 'commande',
    'comment': 'commentaire',
    'commercial': 'commercial',
    'commission': 'commission',
    'commit': 'commettre',
    'commitment': 'engagement',
    'committee': 'comité',
    'common': 'commun',
    'communicate': 'communiquer',
    'communication': 'communication',
    'community': 'communauté',
    'company': 'entreprise',
    'compare': 'comparer',
    'comparison': 'comparaison',
    'compete': 'concourir',
    'competition': 'compétition',
    'competitive': 'compétitif',
    'competitor': 'concurrent',
    'complain': 'se plaindre',
    'complaint': 'plainte',
    'complete': 'complet',
    'completely': 'complètement',
    'complex': 'complexe',
    'complicated': 'compliqué',
    'component': 'composant',
    'compose': 'composer',
    'computer': 'ordinateur',
    'concentrate': 'concentrer',
    'concentration': 'concentration',
    'concept': 'concept',
    'concern': 'inquiétude',
    'concerned': 'inquiet',
    'concert': 'concert',
    'conclude': 'conclure',
    'conclusion': 'conclusion',
    'concrete': 'béton',
    'condition': 'condition',
    'conduct': 'conduire',
    'conference': 'conférence',
    'confidence': 'confiance',
    'confident': 'confiant',
    'confirm': 'confirmer',
    'conflict': 'conflit',
    'confront': 'confronter',
    'confusion': 'confusion',
    'congress': 'congrès',
    'connect': 'connecter',
    'connection': 'connexion',
    'consciousness': 'conscience',
    'consequence': 'conséquence',
    'conservative': 'conservateur',
    'consider': 'considérer',
    'consideration': 'considération',
    'consist': 'consister',
    'consistent': 'cohérent',
    'constant': 'constant',
    'constantly': 'constamment',
    'constitute': 'constituer',
    'constitution': 'constitution',
    'construct': 'construire',
    'construction': 'construction',
    'consultant': 'consultant',
    'consume': 'consommer',
    'consumer': 'consommateur',
    'contact': 'contact',
    'contain': 'contenir',
    'container': 'conteneur',
    'contemporary': 'contemporain',
    'content': 'contenu',
    'contest': 'concours',
    'context': 'contexte',
    'continue': 'continuer',
    'continued': 'continué',
    'contract': 'contrat',
    'contractor': 'entrepreneur',
    'contrast': 'contraste',
    'contribute': 'contribuer',
    'contribution': 'contribution',
    'control': 'contrôle',
    'controversial': 'controversé',
    'controversy': 'controverse',
    'convention': 'convention',
    'conventional': 'conventionnel',
    'conversation': 'conversation',
    'convert': 'convertir',
    'convince': 'convaincre',
    'cook': 'cuisiner',
    'cookie': 'biscuit',
    'cooking': 'cuisine',
    'cool': 'frais',
    'cooperation': 'coopération',
    'cope': 'faire face',
    'copy': 'copie',
    'core': 'noyau',
    'corn': 'maïs',
    'corner': 'coin',
    'corporate': 'corporatif',
    'corporation': 'société',
    'correct': 'correct',
    'cost': 'coût',
    'cotton': 'coton',
    'couch': 'canapé',
    'could': 'pourrait',
    'council': 'conseil',
    'count': 'compter',
    'counter': 'comptoir',
    'country': 'pays',
    'county': 'comté',
    'couple': 'couple',
    'courage': 'courage',
    'course': 'cours',
    'court': 'tribunal',
    'cousin': 'cousin',
    'cover': 'couvrir',
    'coverage': 'couverture',
    'cow': 'vache',
    'crack': 'fissure',
    'craft': 'artisanat',
    'crash': 'accident',
    'crazy': 'fou',
    'cream': 'crème',
    'create': 'créer',
    'creation': 'création',
    'creative': 'créatif',
    'creature': 'créature',
    'credit': 'crédit',
    'crew': 'équipage',
    'crime': 'crime',
    'criminal': 'criminel',
    'crisis': 'crise',
    'criteria': 'critères',
    'critic': 'critique',
    'critical': 'critique',
    'criticism': 'critique',
    'criticize': 'critiquer',
    'crop': 'récolte',
    'cross': 'croix',
    'crowd': 'foule',
    'crucial': 'crucial',
    'cry': 'pleurer',
    'cultural': 'culturel',
    'culture': 'culture',
    'cup': 'tasse',
    'curious': 'curieux',
    'current': 'actuel',
    'currently': 'actuellement',
    'curve': 'courbe',
    'custom': 'coutume',
    'customer': 'client',
    'cut': 'couper',
    'cycle': 'cycle'
};

// Fonction pour appliquer les corrections en lot
function massiveCorrection() {
    let corrected = 0;

    for (const [word, translation] of Object.entries(massiveTranslationDict)) {
        try {
            const stmt = db.db.prepare(`
                UPDATE words 
                SET translation = ?, 
                    updated_at = CURRENT_TIMESTAMP
                WHERE word = ? AND translation = ?
            `);

            const result = stmt.run(translation, word, `[${word}]`);

            if (result.changes > 0) {
                console.log(`✅ ${word} -> ${translation}`);
                corrected++;
            }
        } catch (error) {
            console.error(`❌ Erreur pour "${word}":`, error.message);
        }
    }

    return corrected;
}

console.log('\n🚀 Application de la correction massive...');
const corrected = massiveCorrection();

// Vérification finale
const finalStats = {
    total: db.db.prepare('SELECT COUNT(*) as count FROM words').get().count,
    translated: db.db.prepare('SELECT COUNT(*) as count FROM words WHERE translation NOT LIKE \'[%]\'').get().count,
    untranslated: db.db.prepare('SELECT COUNT(*) as count FROM words WHERE translation LIKE \'[%]\'').get().count
};

console.log(`\n📊 Résumé de la correction massive:`);
console.log(`   ✅ Mots corrigés dans cette session: ${corrected}`);
console.log(`   📚 Total des mots: ${finalStats.total}`);
console.log(`   ✅ Mots traduits: ${finalStats.translated} (${Math.round(finalStats.translated / finalStats.total * 100)}%)`);
console.log(`   ⚠️  Mots non traduits restants: ${finalStats.untranslated} (${Math.round(finalStats.untranslated / finalStats.total * 100)}%)`);

console.log('\n🎉 Correction massive terminée ! L\'application devrait être beaucoup plus complète maintenant.');

db.db.close();
