import Database from 'better-sqlite3';

// Ouvrir la base de données
const db = new Database('english-app.db');

console.log('🔍 Traduction massive - Lot 3 (finition complète)...\n');

// Récupérer tous les mots restants
const remainingWords = db.prepare('SELECT word FROM words WHERE translation = ?').all('[ ]');
console.log(`📝 ${remainingWords.length} mots restants à traduire...\n`);

// Traductions pour tous les mots restants
const translations_batch3 = {
    'african-american': 'afro-américain',
    'audience': 'public',
    'bake': 'cuire au four',
    'balance': 'équilibre',
    'basket': 'panier',
    'bench': 'banc',
    'besides': 'en plus',
    'bible': 'bible',
    'bombing': 'bombardement',
    'branch': 'branche',
    'bubble': 'bulle',
    'budget': 'budget',
    'builder': 'constructeur',
    'burden': 'fardeau',
    'bury': 'enterrer',
    'businessman': 'homme d\'affaires',
    'button': 'bouton',
    'buyer': 'acheteur',
    'cabinet': 'armoire',
    'cable': 'câble',
    'calculate': 'calculer',
    'calculation': 'calcul',
    'campaign': 'campagne',
    'campus': 'campus',
    'can': 'pouvoir',
    'canal': 'canal',
    'cancer': 'cancer',
    'candidate': 'candidat',
    'cap': 'casquette',
    'capable': 'capable',
    'capacity': 'capacité',
    'capital': 'capital',
    'captain': 'capitaine',
    'capture': 'capturer',
    'carbon': 'carbone',
    'card': 'carte',
    'career': 'carrière',
    'careful': 'prudent',
    'carefully': 'soigneusement',
    'carpet': 'tapis',
    'carry': 'porter',
    'cartoon': 'dessin animé',
    'case': 'cas',
    'cash': 'argent liquide',
    'cast': 'jeter',
    'castle': 'château',
    'cat': 'chat',
    'catch': 'attraper',
    'category': 'catégorie',
    'catholic': 'catholique',
    'cattle': 'bétail',
    'cause': 'cause',
    'cave': 'grotte',
    'ceiling': 'plafond',
    'celebrate': 'célébrer',
    'celebration': 'célébration',
    'celebrity': 'célébrité',
    'cell': 'cellule',
    'census': 'recensement',
    'center': 'centre',
    'central': 'central',
    'centre': 'centre',
    'century': 'siècle',
    'ceremony': 'cérémonie',
    'certain': 'certain',
    'certainly': 'certainement',
    'chain': 'chaîne',
    'chair': 'chaise',
    'chairman': 'président',
    'challenge': 'défi',
    'champion': 'champion',
    'championship': 'championnat',
    'chance': 'chance',
    'change': 'changer',
    'channel': 'chaîne',
    'chapter': 'chapitre',
    'character': 'caractère',
    'characteristic': 'caractéristique',
    'charge': 'charger',
    'charity': 'charité',
    'chart': 'graphique',
    'chase': 'poursuivre',
    'cheap': 'bon marché',
    'check': 'vérifier',
    'cheese': 'fromage',
    'chemical': 'chimique',
    'chemistry': 'chimie',
    'chess': 'échecs',
    'chest': 'poitrine',
    'chicken': 'poulet',
    'chief': 'chef',
    'child': 'enfant',
    'childhood': 'enfance',
    'chip': 'puce',
    'chocolate': 'chocolat',
    'choice': 'choix',
    'choose': 'choisir',
    'christian': 'chrétien',
    'christmas': 'noël',
    'church': 'église',
    'cigarette': 'cigarette',
    'cinema': 'cinéma',
    'circle': 'cercle',
    'circumstance': 'circonstance',
    'citizen': 'citoyen',
    'city': 'ville',
    'civil': 'civil',
    'civilian': 'civil',
    'claim': 'réclamer',
    'class': 'classe',
    'classic': 'classique',
    'classroom': 'salle de classe',
    'clean': 'propre',
    'clear': 'clair',
    'clearly': 'clairement',
    'client': 'client',
    'climate': 'climat',
    'climb': 'grimper',
    'clock': 'horloge',
    'close': 'fermer',
    'closed': 'fermé',
    'closely': 'étroitement',
    'closer': 'plus près',
    'closet': 'placard',
    'clothes': 'vêtements',
    'clothing': 'vêtements',
    'cloud': 'nuage',
    'club': 'club',
    'clue': 'indice',
    'coach': 'entraîneur',
    'coal': 'charbon',
    'coast': 'côte',
    'coat': 'manteau',
    'code': 'code',
    'coffee': 'café',
    'coin': 'pièce',
    'cold': 'froid',
    'collapse': 'effondrement',
    'colleague': 'collègue',
    'collect': 'collecter',
    'collection': 'collection',
    'college': 'université',
    'color': 'couleur',
    'colored': 'coloré',
    'column': 'colonne',
    'combination': 'combinaison',
    'combine': 'combiner',
    'come': 'venir',
    'comedy': 'comédie',
    'comfort': 'confort',
    'comfortable': 'confortable',
    'command': 'commande',
    'comment': 'commentaire',
    'commercial': 'commercial',
    'commission': 'commission',
    'commit': 'commettre',
    'commitment': 'engagement',
    'committee': 'comité',
    'common': 'commun',
    'commonly': 'communément',
    'communicate': 'communiquer',
    'communication': 'communication',
    'community': 'communauté',
    'company': 'entreprise',
    'compare': 'comparer',
    'comparison': 'comparaison',
    'compete': 'concourir',
    'competition': 'compétition',
    'competitive': 'compétitif',
    'competitor': 'concurrent',
    'complain': 'se plaindre',
    'complaint': 'plainte',
    'complete': 'complet',
    'completely': 'complètement',
    'complex': 'complexe',
    'component': 'composant',
    'computer': 'ordinateur',
    'concentrate': 'se concentrer',
    'concentration': 'concentration',
    'concept': 'concept',
    'concern': 'préoccupation',
    'concerned': 'préoccupé',
    'concert': 'concert',
    'conclude': 'conclure',
    'conclusion': 'conclusion',
    'condition': 'condition',
    'conduct': 'conduire',
    'conference': 'conférence',
    'confidence': 'confiance',
    'confident': 'confiant',
    'confirm': 'confirmer',
    'conflict': 'conflit',
    'confused': 'confus',
    'confusing': 'déroutant',
    'confusion': 'confusion',
    'congress': 'congrès',
    'connect': 'connecter',
    'connection': 'connexion',
    'conscious': 'conscient',
    'consequence': 'conséquence',
    'conservative': 'conservateur',
    'consider': 'considérer',
    'considerable': 'considérable',
    'consideration': 'considération',
    'consist': 'consister',
    'consistent': 'cohérent',
    'constant': 'constant',
    'constantly': 'constamment',
    'constitute': 'constituer',
    'construction': 'construction',
    'consume': 'consommer',
    'consumer': 'consommateur',
    'consumption': 'consommation',
    'contact': 'contact',
    'contain': 'contenir',
    'container': 'conteneur',
    'contemporary': 'contemporain',
    'content': 'contenu',
    'contest': 'concours',
    'context': 'contexte',
    'continue': 'continuer',
    'continued': 'continué',
    'contract': 'contrat',
    'contrast': 'contraste',
    'contribute': 'contribuer',
    'contribution': 'contribution',
    'control': 'contrôle',
    'controversial': 'controversé',
    'controversy': 'controverse',
    'convention': 'convention',
    'conventional': 'conventionnel',
    'conversation': 'conversation',
    'convert': 'convertir',
    'convince': 'convaincre',
    'cook': 'cuisiner',
    'cookie': 'biscuit',
    'cooking': 'cuisine',
    'cool': 'frais',
    'cooperation': 'coopération',
    'cope': 'faire face',
    'copy': 'copie',
    'core': 'noyau',
    'corn': 'maïs',
    'corner': 'coin',
    'corporate': 'entreprise',
    'corporation': 'société',
    'correct': 'correct',
    'correctly': 'correctement',
    'cost': 'coût',
    'cotton': 'coton',
    'could': 'pourrait',
    'council': 'conseil',
    'count': 'compter',
    'counter': 'compteur',
    'country': 'pays',
    'county': 'comté',
    'couple': 'couple',
    'courage': 'courage',
    'course': 'cours',
    'court': 'tribunal',
    'cousin': 'cousin',
    'cover': 'couvrir',
    'coverage': 'couverture',
    'cow': 'vache',
    'crack': 'fissure',
    'craft': 'artisanat',
    'crash': 'accident',
    'crazy': 'fou',
    'cream': 'crème',
    'create': 'créer',
    'creation': 'création',
    'creative': 'créatif',
    'creator': 'créateur',
    'creature': 'créature',
    'credit': 'crédit',
    'crew': 'équipage',
    'crime': 'crime',
    'criminal': 'criminel',
    'crisis': 'crise',
    'criteria': 'critères',
    'critic': 'critique',
    'critical': 'critique',
    'criticism': 'critique',
    'criticize': 'critiquer',
    'crop': 'récolte',
    'cross': 'croix',
    'crowd': 'foule',
    'crucial': 'crucial',
    'cruise': 'croisière',
    'cry': 'pleurer',
    'cultural': 'culturel',
    'culture': 'culture',
    'cup': 'tasse',
    'curious': 'curieux',
    'current': 'actuel',
    'currently': 'actuellement',
    'curve': 'courbe',
    'custom': 'coutume',
    'customer': 'client',
    'cut': 'couper',
    'cycle': 'cycle',
    'dad': 'papa',
    'daily': 'quotidien',
    'damage': 'dommage',
    'dance': 'danse',
    'dancing': 'danse',
    'danger': 'danger',
    'dangerous': 'dangereux',
    'dare': 'oser',
    'dark': 'sombre',
    'darkness': 'obscurité',
    'data': 'données',
    'database': 'base de données',
    'date': 'date',
    'daughter': 'fille',
    'dawn': 'aube',
    'day': 'jour',
    'dead': 'mort',
    'deadline': 'date limite',
    'deal': 'affaire',
    'dealer': 'concessionnaire',
    'dear': 'cher',
    'death': 'mort',
    'debate': 'débat',
    'debt': 'dette',
    'decade': 'décennie',
    'december': 'décembre',
    'decide': 'décider',
    'decision': 'décision',
    'deck': 'pont',
    'declare': 'déclarer',
    'decline': 'déclin',
    'decrease': 'diminuer',
    'deep': 'profond',
    'deeply': 'profondément',
    'deer': 'cerf',
    'defeat': 'défaite',
    'defend': 'défendre',
    'defense': 'défense',
    'deficit': 'déficit',
    'define': 'définir',
    'definitely': 'définitivement',
    'definition': 'définition',
    'degree': 'degré',
    'deliver': 'livrer',
    'delivery': 'livraison',
    'demand': 'demande',
    'democracy': 'démocratie',
    'democratic': 'démocratique',
    'demonstrate': 'démontrer',
    'demonstration': 'démonstration',
    'department': 'département',
    'depend': 'dépendre',
    'dependent': 'dépendant',
    'depending': 'selon',
    'deposit': 'dépôt',
    'depression': 'dépression',
    'depth': 'profondeur',
    'deputy': 'adjoint',
    'derive': 'dériver',
    'describe': 'décrire',
    'description': 'description',
    'desert': 'désert',
    'deserve': 'mériter',
    'design': 'conception',
    'designer': 'concepteur',
    'desire': 'désir',
    'desk': 'bureau',
    'desperate': 'désespéré',
    'despite': 'malgré',
    'destroy': 'détruire',
    'destruction': 'destruction',
    'detail': 'détail',
    'detailed': 'détaillé',
    'detect': 'détecter',
    'detective': 'détective',
    'determine': 'déterminer',
    'develop': 'développer',
    'developing': 'en développement',
    'development': 'développement',
    'device': 'appareil',
    'devote': 'consacrer',
    'dialogue': 'dialogue',
    'diamond': 'diamant',
    'diary': 'journal intime',
    'die': 'mourir',
    'diet': 'régime',
    'difference': 'différence',
    'different': 'différent',
    'differently': 'différemment',
    'difficult': 'difficile',
    'difficulty': 'difficulté',
    'digital': 'numérique',
    'dimension': 'dimension',
    'dinner': 'dîner',
    'direct': 'direct',
    'direction': 'direction',
    'directly': 'directement',
    'director': 'directeur',
    'dirty': 'sale',
    'disability': 'handicap',
    'disagree': 'être en désaccord',
    'disappear': 'disparaître',
    'disappoint': 'décevoir',
    'disappointed': 'déçu',
    'disappointing': 'décevant',
    'disappointment': 'déception',
    'disaster': 'catastrophe',
    'discipline': 'discipline',
    'discount': 'remise',
    'discover': 'découvrir',
    'discovery': 'découverte',
    'discuss': 'discuter',
    'discussion': 'discussion',
    'disease': 'maladie',
    'dish': 'plat',
    'disk': 'disque',
    'dismiss': 'licencier',
    'disorder': 'désordre',
    'display': 'affichage',
    'distance': 'distance',
    'distant': 'distant',
    'distinct': 'distinct',
    'distinction': 'distinction',
    'distinguish': 'distinguer',
    'distribute': 'distribuer',
    'distribution': 'distribution',
    'district': 'district',
    'divide': 'diviser',
    'division': 'division',
    'divorce': 'divorce',
    'do': 'faire',
    'doctor': 'médecin',
    'document': 'document',
    'dog': 'chien',
    'dollar': 'dollar',
    'domestic': 'domestique',
    'dominant': 'dominant',
    'dominate': 'dominer',
    'door': 'porte',
    'double': 'double',
    'doubt': 'doute',
    'down': 'en bas',
    'download': 'télécharger',
    'downtown': 'centre-ville',
    'dozen': 'douzaine',
    'draft': 'brouillon',
    'drag': 'traîner',
    'drama': 'drame',
    'dramatic': 'dramatique',
    'dramatically': 'dramatiquement',
    'draw': 'dessiner',
    'drawing': 'dessin',
    'dream': 'rêve',
    'dress': 'robe',
    'dressed': 'habillé',
    'drink': 'boisson',
    'drinking': 'boire',
    'drive': 'conduire',
    'driver': 'conducteur',
    'driving': 'conduite',
    'drop': 'tomber',
    'drug': 'drogue',
    'dry': 'sec',
    'due': 'dû',
    'during': 'pendant',
    'dust': 'poussière',
    'duty': 'devoir',
    'dying': 'mourant',
    'eager': 'impatient',
    'earlier': 'plus tôt',
    'earliest': 'le plus tôt',
    'ear': 'oreille',
    'early': 'tôt',
    'earn': 'gagner',
    'earth': 'terre',
    'earthquake': 'tremblement de terre',
    'easily': 'facilement',
    'east': 'est',
    'eastern': 'oriental',
    'easy': 'facile',
    'eat': 'manger',
    'eating': 'manger',
    'economic': 'économique',
    'economics': 'économie',
    'economist': 'économiste',
    'economy': 'économie',
    'edge': 'bord',
    'edit': 'modifier',
    'edition': 'édition',
    'editor': 'éditeur',
    'educate': 'éduquer',
    'educated': 'éduqué',
    'education': 'éducation',
    'educational': 'éducatif',
    'effect': 'effet',
    'effective': 'efficace',
    'effectively': 'efficacement',
    'efficiency': 'efficacité',
    'efficient': 'efficace',
    'effort': 'effort',
    'egg': 'œuf',
    'eight': 'huit',
    'eighteen': 'dix-huit',
    'eighth': 'huitième',
    'eighty': 'quatre-vingts',
    'either': 'soit',
    'elderly': 'âgé',
    'elect': 'élire',
    'election': 'élection',
    'electric': 'électrique',
    'electrical': 'électrique',
    'electricity': 'électricité',
    'electronic': 'électronique',
    'element': 'élément',
    'elementary': 'élémentaire',
    'elephant': 'éléphant',
    'elevator': 'ascenseur',
    'eleven': 'onze',
    'eliminate': 'éliminer',
    'else': 'autre',
    'elsewhere': 'ailleurs',
    'emerge': 'émerger',
    'emergency': 'urgence',
    'emission': 'émission',
    'emotion': 'émotion',
    'emotional': 'émotionnel',
    'emphasis': 'emphase',
    'emphasize': 'souligner',
    'empire': 'empire',
    'employ': 'employer',
    'employee': 'employé',
    'employer': 'employeur',
    'employment': 'emploi',
    'empty': 'vide',
    'enable': 'permettre',
    'encounter': 'rencontrer',
    'encourage': 'encourager',
    'encouragement': 'encouragement',
    'end': 'fin',
    'ending': 'fin',
    'enemy': 'ennemi',
    'energy': 'énergie',
    'enforce': 'faire respecter',
    'engage': 'engager',
    'engaged': 'fiancé',
    'engagement': 'engagement',
    'engine': 'moteur',
    'engineer': 'ingénieur',
    'engineering': 'ingénierie',
    'enhance': 'améliorer',
    'enjoy': 'profiter',
    'enjoyable': 'agréable',
    'enormous': 'énorme',
    'enough': 'assez',
    'ensure': 'assurer',
    'enter': 'entrer',
    'enterprise': 'entreprise',
    'entertain': 'divertir',
    'entertaining': 'divertissant',
    'entertainment': 'divertissement',
    'enthusiasm': 'enthousiasme',
    'enthusiastic': 'enthousiaste',
    'entire': 'entier',
    'entirely': 'entièrement',
    'entrance': 'entrée',
    'entry': 'entrée',
    'environment': 'environnement',
    'environmental': 'environnemental',
    'episode': 'épisode',
    'equal': 'égal',
    'equally': 'également',
    'equipment': 'équipement',
    'equivalent': 'équivalent',
    'era': 'ère',
    'error': 'erreur',
    'escape': 'échapper',
    'especially': 'surtout',
    'essential': 'essentiel',
    'essentially': 'essentiellement',
    'establish': 'établir',
    'establishment': 'établissement',
    'estate': 'propriété',
    'estimate': 'estimer',
    'etc': 'etc',
    'ethics': 'éthique',
    'ethnic': 'ethnique',
    'european': 'européen',
    'evaluate': 'évaluer',
    'evaluation': 'évaluation',
    'even': 'même',
    'evening': 'soir',
    'event': 'événement',
    'eventually': 'finalement',
    'ever': 'jamais',
    'every': 'chaque',
    'everybody': 'tout le monde',
    'everyday': 'quotidien',
    'everyone': 'tout le monde',
    'everything': 'tout',
    'everywhere': 'partout',
    'evidence': 'preuve',
    'evident': 'évident',
    'evil': 'mal',
    'exact': 'exact',
    'exactly': 'exactement',
    'exam': 'examen',
    'examination': 'examen',
    'examine': 'examiner',
    'example': 'exemple',
    'exceed': 'dépasser',
    'excellent': 'excellent',
    'except': 'sauf',
    'exception': 'exception',
    'exchange': 'échange',
    'excited': 'excité',
    'excitement': 'excitation',
    'exciting': 'excitant',
    'exclude': 'exclure',
    'excuse': 'excuse',
    'executive': 'cadre',
    'exercise': 'exercice',
    'exhibit': 'exposer',
    'exhibition': 'exposition',
    'exist': 'exister',
    'existence': 'existence',
    'existing': 'existant',
    'exit': 'sortie',
    'expand': 'étendre',
    'expansion': 'expansion',
    'expect': 's\'attendre',
    'expectation': 'attente',
    'expected': 'attendu',
    'expedition': 'expédition',
    'expense': 'dépense',
    'expensive': 'cher',
    'experience': 'expérience',
    'experienced': 'expérimenté',
    'experiment': 'expérience',
    'expert': 'expert',
    'expertise': 'expertise',
    'explain': 'expliquer',
    'explanation': 'explication',
    'explode': 'exploser',
    'exploration': 'exploration',
    'explore': 'explorer',
    'explosion': 'explosion',
    'export': 'exporter',
    'expose': 'exposer',
    'exposure': 'exposition',
    'express': 'exprimer',
    'expression': 'expression',
    'extend': 'étendre',
    'extension': 'extension',
    'extensive': 'étendu',
    'extent': 'mesure',
    'external': 'externe',
    'extra': 'supplémentaire',
    'extraordinary': 'extraordinaire',
    'extreme': 'extrême',
    'extremely': 'extrêmement',
    'eye': 'œil'
};

console.log(`📝 Ajout de ${Object.keys(translations_batch3).length} traductions finales...\n`);

const updateStmt = db.prepare('UPDATE words SET translation = ? WHERE word = ? AND translation = ?');
let updated = 0;

for (const [word, translation] of Object.entries(translations_batch3)) {
    const result = updateStmt.run(translation, word, '[ ]');
    if (result.changes > 0) {
        updated++;
        if (updated <= 20) {
            console.log(`✅ ${word} → ${translation}`);
        }
    }
}

if (updated > 20) {
    console.log(`... et ${updated - 20} autres traductions`);
}

console.log(`\n🎯 ${updated} traductions finales ajoutées avec succès`);

// Statistiques finales
const stats = db.prepare(`
    SELECT 
        COUNT(*) as total,
        COUNT(CASE WHEN translation != '[ ]' THEN 1 END) as with_real_translation,
        COUNT(CASE WHEN translation = '[ ]' THEN 1 END) as without_translation
    FROM words
`).get();

console.log('\n📈 Statistiques finales:');
console.log(`- Total des mots: ${stats.total}`);
console.log(`- Avec vraie traduction: ${stats.with_real_translation}`);
console.log(`- Sans traduction ([ ]): ${stats.without_translation}`);
console.log(`- Pourcentage traduit: ${((stats.with_real_translation / stats.total) * 100).toFixed(1)}%`);

if (stats.without_translation > 0) {
    console.log('\n🔍 Mots restants non traduits:');
    const remaining = db.prepare('SELECT word FROM words WHERE translation = ? LIMIT 20').all('[ ]');
    remaining.forEach((row, index) => {
        console.log(`${index + 1}. ${row.word}`);
    });
    if (stats.without_translation > 20) {
        console.log(`... et ${stats.without_translation - 20} autres`);
    }
}

db.close();
console.log('\n✅ Lot 3 terminé - Traduction finale complétée!');
