import Database from 'better-sqlite3';

// Ouvrir la base de données
const db = new Database('english-app.db');

console.log('🔍 Traduction massive - Lot 4 (derniers mots)...\n');

// Traductions pour les mots restants
const translations_batch4 = {
    'british': 'britannique',
    'buck': 'mâle',
    'bunch': 'groupe',
    'cabin': 'cabine',
    'canadian': 'canadien',
    'carrier': 'transporteur',
    'ceo': 'PDG',
    'changing': 'changeant',
    'chef': 'chef cuisinier',
    'chinese': 'chinois',
    'cholesterol': 'cholestérol',
    'clinical': 'clinique',
    'cluster': 'groupe',
    'coalition': 'coalition',
    'cognitive': 'cognitif',
    'collective': 'collectif',
    'colonial': 'colonial',
    'commander': 'commandant',
    'composition': 'composition',
    'comprehensive': 'complet',
    'concentrate': 'se concentrer',
    'concentration': 'concentration',
    'conception': 'conception',
    'conclude': 'conclure',
    'conclusion': 'conclusion',
    'concrete': 'béton',
    'conference': 'conférence',
    'configure': 'configurer',
    'confirmation': 'confirmation',
    'confirm': 'confirmer',
    'conflict': 'conflit',
    'confront': 'confronter',
    'confusion': 'confusion',
    'congress': 'congrès',
    'congressional': 'du congrès',
    'connect': 'connecter',
    'connection': 'connexion',
    'consciousness': 'conscience',
    'consensus': 'consensus',
    'consent': 'consentement',
    'consequence': 'conséquence',
    'consequently': 'par conséquent',
    'conservation': 'conservation',
    'conservative': 'conservateur',
    'conserve': 'conserver',
    'consider': 'considérer',
    'considerable': 'considérable',
    'considerably': 'considérablement',
    'consideration': 'considération',
    'consist': 'consister',
    'consistent': 'cohérent',
    'consistently': 'de manière cohérente',
    'conspiracy': 'conspiration',
    'constant': 'constant',
    'constantly': 'constamment',
    'constitute': 'constituer',
    'constitution': 'constitution',
    'constitutional': 'constitutionnel',
    'constraint': 'contrainte',
    'construct': 'construire',
    'construction': 'construction',
    'consultation': 'consultation',
    'consume': 'consommer',
    'consumer': 'consommateur',
    'consumption': 'consommation',
    'contact': 'contact',
    'contain': 'contenir',
    'container': 'conteneur',
    'contemporary': 'contemporain',
    'content': 'contenu',
    'contest': 'concours',
    'context': 'contexte',
    'continent': 'continent',
    'continue': 'continuer',
    'continued': 'continué',
    'continuing': 'continu',
    'continuous': 'continu',
    'continuously': 'continuellement',
    'contract': 'contrat',
    'contractor': 'entrepreneur',
    'contrary': 'contraire',
    'contrast': 'contraste',
    'contribute': 'contribuer',
    'contribution': 'contribution',
    'control': 'contrôle',
    'controversial': 'controversé',
    'controversy': 'controverse',
    'convention': 'convention',
    'conventional': 'conventionnel',
    'conversation': 'conversation',
    'convert': 'convertir',
    'conviction': 'conviction',
    'convince': 'convaincre',
    'cook': 'cuisiner',
    'cookie': 'biscuit',
    'cooking': 'cuisine',
    'cool': 'frais',
    'cooperation': 'coopération',
    'cooperative': 'coopératif',
    'cope': 'faire face',
    'copy': 'copie',
    'core': 'noyau',
    'corn': 'maïs',
    'corner': 'coin',
    'corporate': 'd\'entreprise',
    'corporation': 'société',
    'correct': 'correct',
    'correction': 'correction',
    'correctly': 'correctement',
    'correlation': 'corrélation',
    'correspondent': 'correspondant',
    'corresponding': 'correspondant',
    'corrupt': 'corrompu',
    'corruption': 'corruption',
    'cost': 'coût',
    'costume': 'costume',
    'cotton': 'coton',
    'couch': 'canapé',
    'could': 'pourrait',
    'council': 'conseil',
    'count': 'compter',
    'counter': 'compteur',
    'counterpart': 'homologue',
    'countless': 'innombrable',
    'country': 'pays',
    'county': 'comté',
    'couple': 'couple',
    'courage': 'courage',
    'course': 'cours',
    'court': 'tribunal',
    'courtesy': 'courtoisie',
    'cousin': 'cousin',
    'cover': 'couvrir',
    'coverage': 'couverture',
    'cow': 'vache',
    'crack': 'fissure',
    'craft': 'artisanat',
    'crash': 'accident',
    'crazy': 'fou',
    'cream': 'crème',
    'create': 'créer',
    'creation': 'création',
    'creative': 'créatif',
    'creativity': 'créativité',
    'creator': 'créateur',
    'creature': 'créature',
    'credibility': 'crédibilité',
    'credit': 'crédit',
    'crew': 'équipage',
    'crime': 'crime',
    'criminal': 'criminel',
    'crisis': 'crise',
    'criteria': 'critères',
    'criterion': 'critère',
    'critic': 'critique',
    'critical': 'critique',
    'critically': 'de manière critique',
    'criticism': 'critique',
    'criticize': 'critiquer',
    'crop': 'récolte',
    'cross': 'croix',
    'crossing': 'traversée',
    'crowd': 'foule',
    'crucial': 'crucial',
    'cruise': 'croisière',
    'cry': 'pleurer',
    'crystal': 'cristal',
    'cultural': 'culturel',
    'culture': 'culture',
    'cup': 'tasse',
    'curious': 'curieux',
    'currency': 'devise',
    'current': 'actuel',
    'currently': 'actuellement',
    'curve': 'courbe',
    'custom': 'coutume',
    'customer': 'client',
    'cut': 'couper',
    'cutting': 'coupe',
    'cycle': 'cycle',
    'dad': 'papa',
    'daily': 'quotidien',
    'damage': 'dommage',
    'dance': 'danse',
    'dancing': 'danse',
    'danger': 'danger',
    'dangerous': 'dangereux',
    'dare': 'oser',
    'dark': 'sombre',
    'darkness': 'obscurité',
    'data': 'données',
    'database': 'base de données',
    'date': 'date',
    'dating': 'rencontres',
    'daughter': 'fille',
    'dawn': 'aube',
    'day': 'jour',
    'dead': 'mort',
    'deadline': 'date limite',
    'deadly': 'mortel',
    'deal': 'affaire',
    'dealer': 'concessionnaire',
    'dealing': 'transaction',
    'dear': 'cher',
    'death': 'mort',
    'debate': 'débat',
    'debt': 'dette',
    'decade': 'décennie',
    'december': 'décembre',
    'decent': 'décent',
    'decide': 'décider',
    'decision': 'décision',
    'deck': 'pont',
    'declaration': 'déclaration',
    'declare': 'déclarer',
    'decline': 'déclin',
    'decrease': 'diminuer',
    'deep': 'profond',
    'deeply': 'profondément',
    'deer': 'cerf',
    'defeat': 'défaite',
    'defend': 'défendre',
    'defendant': 'accusé',
    'defense': 'défense',
    'defensive': 'défensif',
    'deficit': 'déficit',
    'define': 'définir',
    'definitely': 'définitivement',
    'definition': 'définition',
    'degree': 'degré',
    'delay': 'retard',
    'delegate': 'délégué',
    'delegation': 'délégation',
    'delete': 'supprimer',
    'deliberately': 'délibérément',
    'deliver': 'livrer',
    'delivery': 'livraison',
    'demand': 'demande',
    'democracy': 'démocratie',
    'democratic': 'démocratique',
    'demonstrate': 'démontrer',
    'demonstration': 'démonstration',
    'department': 'département',
    'depend': 'dépendre',
    'dependent': 'dépendant',
    'depending': 'selon',
    'deployment': 'déploiement',
    'deposit': 'dépôt',
    'depression': 'dépression',
    'depth': 'profondeur',
    'deputy': 'adjoint',
    'derive': 'dériver',
    'describe': 'décrire',
    'description': 'description',
    'desert': 'désert',
    'deserve': 'mériter',
    'design': 'conception',
    'designer': 'concepteur',
    'desire': 'désir',
    'desk': 'bureau',
    'desperate': 'désespéré',
    'despite': 'malgré',
    'destroy': 'détruire',
    'destruction': 'destruction',
    'detail': 'détail',
    'detailed': 'détaillé',
    'detect': 'détecter',
    'detection': 'détection',
    'detective': 'détective',
    'determine': 'déterminer',
    'develop': 'développer',
    'developing': 'en développement',
    'development': 'développement',
    'device': 'appareil',
    'devote': 'consacrer',
    'dialogue': 'dialogue',
    'diamond': 'diamant',
    'diary': 'journal intime',
    'dick': 'pénis',
    'dictionary': 'dictionnaire',
    'die': 'mourir',
    'diet': 'régime',
    'differ': 'différer',
    'difference': 'différence',
    'different': 'différent',
    'differently': 'différemment',
    'difficult': 'difficile',
    'difficulty': 'difficulté',
    'digital': 'numérique',
    'dimension': 'dimension',
    'dining': 'repas',
    'dinner': 'dîner',
    'direct': 'direct',
    'direction': 'direction',
    'directly': 'directement',
    'director': 'directeur',
    'directory': 'répertoire',
    'dirty': 'sale',
    'disability': 'handicap',
    'disagree': 'être en désaccord',
    'disappear': 'disparaître',
    'disappointed': 'déçu',
    'disappointing': 'décevant',
    'disappointment': 'déception',
    'disaster': 'catastrophe',
    'discipline': 'discipline',
    'discount': 'remise',
    'discover': 'découvrir',
    'discovery': 'découverte',
    'discrimination': 'discrimination',
    'discuss': 'discuter',
    'discussion': 'discussion',
    'disease': 'maladie',
    'dish': 'plat',
    'disk': 'disque',
    'dismiss': 'licencier',
    'disorder': 'désordre',
    'display': 'affichage',
    'distance': 'distance',
    'distant': 'distant',
    'distinct': 'distinct',
    'distinction': 'distinction',
    'distinguish': 'distinguer',
    'distribute': 'distribuer',
    'distribution': 'distribution',
    'district': 'district',
    'divide': 'diviser',
    'division': 'division',
    'divorce': 'divorce',
    'do': 'faire',
    'dock': 'quai',
    'doctor': 'médecin',
    'document': 'document',
    'documentary': 'documentaire',
    'dog': 'chien',
    'dollar': 'dollar',
    'domain': 'domaine',
    'domestic': 'domestique',
    'dominant': 'dominant',
    'dominate': 'dominer',
    'door': 'porte',
    'double': 'double',
    'doubt': 'doute',
    'down': 'en bas',
    'downtown': 'centre-ville',
    'dozen': 'douzaine',
    'draft': 'brouillon',
    'drag': 'traîner',
    'drama': 'drame',
    'dramatic': 'dramatique',
    'dramatically': 'dramatiquement',
    'draw': 'dessiner',
    'drawing': 'dessin',
    'dream': 'rêve',
    'dress': 'robe',
    'dressed': 'habillé',
    'dressing': 'habillage',
    'drink': 'boisson',
    'drinking': 'boire',
    'drive': 'conduire',
    'driver': 'conducteur',
    'driving': 'conduite',
    'drop': 'tomber',
    'drug': 'drogue',
    'dry': 'sec',
    'duck': 'canard',
    'due': 'dû',
    'during': 'pendant',
    'dust': 'poussière',
    'duty': 'devoir',
    'dying': 'mourant',
    'dynamic': 'dynamique',
    'earth': 'terre',
    'ease': 'facilité',
    'easily': 'facilement',
    'east': 'est',
    'eastern': 'oriental',
    'easy': 'facile',
    'eat': 'manger',
    'eating': 'manger',
    'echo': 'écho',
    'economic': 'économique',
    'economics': 'économie',
    'economist': 'économiste',
    'economy': 'économie',
    'edition': 'édition',
    'editor': 'éditeur',
    'editorial': 'éditorial',
    'education': 'éducation',
    'educational': 'éducatif',
    'educator': 'éducateur',
    'effect': 'effet',
    'effective': 'efficace',
    'effectively': 'efficacement',
    'effectiveness': 'efficacité',
    'efficiency': 'efficacité',
    'efficient': 'efficace',
    'efficiently': 'efficacement',
    'effort': 'effort',
    'egg': 'œuf',
    'eight': 'huit',
    'eighteen': 'dix-huit',
    'eighth': 'huitième',
    'eighty': 'quatre-vingts',
    'either': 'soit',
    'elderly': 'âgé',
    'elect': 'élire',
    'election': 'élection',
    'electric': 'électrique',
    'electrical': 'électrique',
    'electricity': 'électricité',
    'electronic': 'électronique',
    'electronics': 'électronique',
    'element': 'élément',
    'elementary': 'élémentaire',
    'elephant': 'éléphant',
    'elevator': 'ascenseur',
    'eleven': 'onze',
    'eliminate': 'éliminer',
    'elimination': 'élimination',
    'elite': 'élite',
    'else': 'autre',
    'elsewhere': 'ailleurs',
    'emerge': 'émerger',
    'emergency': 'urgence',
    'emission': 'émission',
    'emotion': 'émotion',
    'emotional': 'émotionnel',
    'emotionally': 'émotionnellement',
    'emphasis': 'emphase',
    'emphasize': 'souligner',
    'empire': 'empire',
    'employ': 'employer',
    'employee': 'employé',
    'employer': 'employeur',
    'employment': 'emploi',
    'empty': 'vide',
    'enable': 'permettre',
    'encounter': 'rencontrer',
    'encourage': 'encourager',
    'encouragement': 'encouragement',
    'encouraging': 'encourageant',
    'end': 'fin',
    'ending': 'fin',
    'enemy': 'ennemi',
    'energy': 'énergie',
    'enforcement': 'application',
    'engage': 'engager',
    'engaged': 'fiancé',
    'engagement': 'engagement',
    'engine': 'moteur',
    'engineer': 'ingénieur',
    'engineering': 'ingénierie',
    'enhance': 'améliorer',
    'enjoy': 'profiter',
    'enjoyable': 'agréable',
    'enormous': 'énorme',
    'enough': 'assez',
    'ensure': 'assurer',
    'enter': 'entrer',
    'enterprise': 'entreprise',
    'entertain': 'divertir',
    'entertaining': 'divertissant',
    'entertainment': 'divertissement',
    'enthusiasm': 'enthousiasme',
    'enthusiastic': 'enthousiaste',
    'entire': 'entier',
    'entirely': 'entièrement',
    'entitle': 'donner droit',
    'entrance': 'entrée',
    'entry': 'entrée',
    'environment': 'environnement',
    'environmental': 'environnemental',
    'episode': 'épisode',
    'equal': 'égal',
    'equally': 'également',
    'equation': 'équation',
    'equipment': 'équipement',
    'equivalent': 'équivalent',
    'era': 'ère',
    'error': 'erreur',
    'escape': 'échapper',
    'especially': 'surtout',
    'essay': 'essai',
    'essential': 'essentiel',
    'essentially': 'essentiellement',
    'establish': 'établir',
    'establishment': 'établissement',
    'estate': 'propriété',
    'estimate': 'estimer',
    'etc': 'etc',
    'ethical': 'éthique',
    'ethics': 'éthique',
    'ethnic': 'ethnique',
    'european': 'européen',
    'evaluate': 'évaluer',
    'evaluation': 'évaluation',
    'even': 'même',
    'evening': 'soir',
    'event': 'événement',
    'eventually': 'finalement',
    'ever': 'jamais',
    'every': 'chaque',
    'everybody': 'tout le monde',
    'everyday': 'quotidien',
    'everyone': 'tout le monde',
    'everything': 'tout',
    'everywhere': 'partout',
    'evidence': 'preuve',
    'evident': 'évident',
    'evil': 'mal',
    'evolution': 'évolution',
    'evolve': 'évoluer',
    'exact': 'exact',
    'exactly': 'exactement',
    'exam': 'examen',
    'examination': 'examen',
    'examine': 'examiner',
    'example': 'exemple',
    'exceed': 'dépasser',
    'excellent': 'excellent',
    'except': 'sauf',
    'exception': 'exception',
    'exceptional': 'exceptionnel',
    'exchange': 'échange',
    'excited': 'excité',
    'excitement': 'excitation',
    'exciting': 'excitant',
    'exclude': 'exclure',
    'excuse': 'excuse',
    'execute': 'exécuter',
    'execution': 'exécution',
    'executive': 'cadre',
    'exercise': 'exercice',
    'exhibit': 'exposer',
    'exhibition': 'exposition',
    'exist': 'exister',
    'existence': 'existence',
    'existing': 'existant',
    'exit': 'sortie',
    'expand': 'étendre',
    'expansion': 'expansion',
    'expect': 's\'attendre',
    'expectation': 'attente',
    'expected': 'attendu',
    'expedition': 'expédition',
    'expense': 'dépense',
    'expensive': 'cher',
    'experience': 'expérience',
    'experienced': 'expérimenté',
    'experiment': 'expérience',
    'experimental': 'expérimental',
    'expert': 'expert',
    'expertise': 'expertise',
    'explain': 'expliquer',
    'explanation': 'explication',
    'explode': 'exploser',
    'exploration': 'exploration',
    'explore': 'explorer',
    'explosion': 'explosion',
    'export': 'exporter',
    'expose': 'exposer',
    'exposure': 'exposition',
    'express': 'exprimer',
    'expression': 'expression',
    'extend': 'étendre',
    'extension': 'extension',
    'extensive': 'étendu',
    'extent': 'mesure',
    'external': 'externe',
    'extra': 'supplémentaire',
    'extraordinary': 'extraordinaire',
    'extreme': 'extrême',
    'extremely': 'extrêmement',
    'eye': 'œil'
};

console.log(`📝 Ajout de ${Object.keys(translations_batch4).length} traductions finales...\n`);

const updateStmt = db.prepare('UPDATE words SET translation = ? WHERE word = ? AND translation = ?');
let updated = 0;

for (const [word, translation] of Object.entries(translations_batch4)) {
    const result = updateStmt.run(translation, word, '[ ]');
    if (result.changes > 0) {
        updated++;
        if (updated <= 20) {
            console.log(`✅ ${word} → ${translation}`);
        }
    }
}

if (updated > 20) {
    console.log(`... et ${updated - 20} autres traductions`);
}

console.log(`\n🎯 ${updated} traductions finales ajoutées avec succès`);

// Statistiques finales
const stats = db.prepare(`
    SELECT 
        COUNT(*) as total,
        COUNT(CASE WHEN translation != '[ ]' THEN 1 END) as with_real_translation,
        COUNT(CASE WHEN translation = '[ ]' THEN 1 END) as without_translation
    FROM words
`).get();

console.log('\n📈 Statistiques finales:');
console.log(`- Total des mots: ${stats.total}`);
console.log(`- Avec vraie traduction: ${stats.with_real_translation}`);
console.log(`- Sans traduction ([ ]): ${stats.without_translation}`);
console.log(`- Pourcentage traduit: ${((stats.with_real_translation / stats.total) * 100).toFixed(1)}%`);

// Si il reste des mots, les afficher
if (stats.without_translation > 0) {
    console.log('\n🔍 Mots restants non traduits:');
    const remaining = db.prepare('SELECT word FROM words WHERE translation = ? ORDER BY word LIMIT 50').all('[ ]');
    remaining.forEach((row, index) => {
        console.log(`${index + 1}. ${row.word}`);
    });
    if (stats.without_translation > 50) {
        console.log(`... et ${stats.without_translation - 50} autres`);
    }
} else {
    console.log('\n🎉 FÉLICITATIONS ! Tous les mots ont été traduits !');
}

db.close();
console.log('\n✅ Lot 4 terminé !');
