import { getDatabase } from './database.js';
import { wordsData } from '../../words.js';
import fs from 'fs';
import path from 'path';

class DataMigration {
    constructor() {
        this.db = getDatabase();
    }

    // Migrer les mots existants de words.js
    async migrateWordsData() {
        console.log('🚀 Démarrage de la migration des mots...');

        let imported = 0;
        let skipped = 0;

        for (const word of wordsData) {
            try {
                this.db.insertWord({
                    word: word.word,
                    translation: word.translation,
                    pronunciation: word.pronunciation,
                    partOfSpeech: word.partOfSpeech,
                    definition: word.definition,
                    example: word.example,
                    exampleTranslation: word.exampleTranslation,
                    difficulty: word.difficulty || 'beginner',
                    category: word.category || 'general'
                });
                imported++;
            } catch (error) {
                if (error.code === 'SQLITE_CONSTRAINT_UNIQUE') {
                    skipped++;
                } else {
                    console.error(`❌ Erreur pour le mot "${word.word}":`, error.message);
                }
            }
        }

        console.log(`✅ Migration terminée: ${imported} mots importés, ${skipped} mots ignorés (doublons)`);
        return { imported, skipped };
    }

    // Migrer la liste de 3000 mots en ajoutant des traductions basiques
    async migrate3000Words() {
        console.log('📚 Démarrage de la migration des 3000 mots...');

        const filePath = path.join(process.cwd(), '3000_english_words.txt');

        if (!fs.existsSync(filePath)) {
            console.error('❌ Fichier 3000_english_words.txt non trouvé');
            return { imported: 0, skipped: 0 };
        }

        const content = fs.readFileSync(filePath, 'utf-8');
        const words = content.split('\n').filter(word => word.trim().length > 0);

        let imported = 0;
        let skipped = 0;

        // Dictionnaire de traductions basiques pour les mots les plus courants
        const basicTranslations = {
            'a': 'un/une',
            'abandon': 'abandonner',
            'ability': 'capacité',
            'able': 'capable',
            'about': 'à propos de',
            'above': 'au-dessus',
            'abroad': 'à l\'étranger',
            'absence': 'absence',
            'absolute': 'absolu',
            'absolutely': 'absolument',
            'accept': 'accepter',
            'access': 'accès',
            'accident': 'accident',
            'according': 'selon',
            'account': 'compte',
            'across': 'à travers',
            'action': 'action',
            'activity': 'activité',
            'actually': 'en fait',
            'address': 'adresse',
            'administration': 'administration',
            'admit': 'admettre',
            'adult': 'adulte',
            'advance': 'avancer',
            'advantage': 'avantage',
            'adventure': 'aventure',
            'advice': 'conseil',
            'affect': 'affecter',
            'afford': 'se permettre',
            'afraid': 'avoir peur',
            'after': 'après',
            'afternoon': 'après-midi',
            'again': 'encore',
            'against': 'contre',
            'age': 'âge',
            'agency': 'agence',
            'agent': 'agent',
            'ago': 'il y a',
            'agree': 'être d\'accord',
            'agreement': 'accord',
            'ahead': 'devant',
            'air': 'air',
            'all': 'tout',
            'allow': 'permettre',
            'almost': 'presque',
            'alone': 'seul',
            'along': 'le long de',
            'already': 'déjà',
            'also': 'aussi',
            'although': 'bien que',
            'always': 'toujours',
            'amazing': 'incroyable',
            'among': 'parmi',
            'amount': 'montant',
            'analysis': 'analyse',
            'and': 'et',
            'anger': 'colère',
            'animal': 'animal',
            'anniversary': 'anniversaire',
            'announce': 'annoncer',
            'another': 'autre',
            'answer': 'réponse',
            'any': 'n\'importe quel',
            'anybody': 'n\'importe qui',
            'anyone': 'n\'importe qui',
            'anything': 'n\'importe quoi',
            'anyway': 'de toute façon',
            'anywhere': 'n\'importe où',
            'appear': 'apparaître',
            'apply': 'appliquer',
            'approach': 'approche',
            'area': 'zone',
            'argue': 'argumenter',
            'arm': 'bras',
            'army': 'armée',
            'around': 'autour',
            'arrive': 'arriver',
            'art': 'art',
            'article': 'article',
            'artist': 'artiste',
            'as': 'comme',
            'ask': 'demander',
            'assume': 'supposer',
            'at': 'à',
            'attack': 'attaque',
            'attempt': 'tentative',
            'attend': 'assister',
            'attention': 'attention',
            'attitude': 'attitude',
            'attract': 'attirer',
            'audience': 'public',
            'author': 'auteur',
            'authority': 'autorité',
            'available': 'disponible',
            'avoid': 'éviter',
            'away': 'loin',
            'baby': 'bébé',
            'back': 'dos/retour',
            'bad': 'mauvais',
            'bag': 'sac',
            'ball': 'balle',
            'bank': 'banque',
            'bar': 'bar',
            'base': 'base',
            'basic': 'basique',
            'battle': 'bataille',
            'be': 'être',
            'beat': 'battre',
            'beautiful': 'beau/belle',
            'because': 'parce que',
            'become': 'devenir',
            'bed': 'lit',
            'bedroom': 'chambre',
            'beer': 'bière',
            'before': 'avant',
            'begin': 'commencer',
            'behavior': 'comportement',
            'behind': 'derrière',
            'believe': 'croire',
            'benefit': 'bénéfice',
            'best': 'meilleur',
            'better': 'mieux',
            'between': 'entre',
            'beyond': 'au-delà',
            'big': 'grand',
            'bill': 'facture',
            'billion': 'milliard',
            'bit': 'peu',
            'black': 'noir',
            'blood': 'sang',
            'blow': 'coup',
            'blue': 'bleu',
            'board': 'planche/conseil',
            'boat': 'bateau',
            'body': 'corps',
            'book': 'livre',
            'born': 'né',
            'both': 'les deux',
            'box': 'boîte',
            'boy': 'garçon',
            'break': 'casser',
            'bring': 'apporter',
            'brother': 'frère',
            'budget': 'budget',
            'build': 'construire',
            'building': 'bâtiment',
            'business': 'affaires',
            'but': 'mais',
            'buy': 'acheter',
            'by': 'par',
            'call': 'appeler',
            'camera': 'caméra',
            'campaign': 'campagne',
            'can': 'pouvoir',
            'cancer': 'cancer',
            'candidate': 'candidat',
            'capital': 'capital',
            'car': 'voiture',
            'card': 'carte',
            'care': 'soin',
            'career': 'carrière',
            'carry': 'porter',
            'case': 'cas',
            'catch': 'attraper',
            'cause': 'cause',
            'cell': 'cellule',
            'center': 'centre',
            'central': 'central',
            'century': 'siècle',
            'certain': 'certain',
            'certainly': 'certainement',
            'chair': 'chaise',
            'challenge': 'défi',
            'chance': 'chance',
            'change': 'changement',
            'character': 'caractère',
            'charge': 'charge',
            'check': 'vérifier',
            'child': 'enfant',
            'choice': 'choix',
            'choose': 'choisir',
            'church': 'église',
            'citizen': 'citoyen',
            'city': 'ville',
            'civil': 'civil',
            'claim': 'revendication',
            'class': 'classe',
            'clear': 'clair',
            'clearly': 'clairement',
            'close': 'proche/fermer',
            'coach': 'entraîneur',
            'cold': 'froid',
            'collection': 'collection',
            'college': 'université',
            'color': 'couleur',
            'come': 'venir',
            'commercial': 'commercial',
            'common': 'commun',
            'community': 'communauté',
            'company': 'entreprise',
            'compare': 'comparer',
            'computer': 'ordinateur',
            'concern': 'préoccupation',
            'condition': 'condition',
            'conference': 'conférence',
            'consider': 'considérer',
            'consumer': 'consommateur',
            'contain': 'contenir',
            'continue': 'continuer',
            'control': 'contrôle',
            'cost': 'coût',
            'could': 'pourrait',
            'country': 'pays',
            'couple': 'couple',
            'course': 'cours',
            'court': 'tribunal',
            'cover': 'couvrir',
            'create': 'créer',
            'crime': 'crime',
            'cultural': 'culturel',
            'culture': 'culture',
            'cup': 'tasse',
            'current': 'actuel',
            'customer': 'client',
            'cut': 'couper',
            'dark': 'sombre',
            'data': 'données',
            'date': 'date',
            'daughter': 'fille',
            'day': 'jour',
            'dead': 'mort',
            'deal': 'affaire',
            'death': 'mort',
            'debate': 'débat',
            'decade': 'décennie',
            'decide': 'décider',
            'decision': 'décision',
            'deep': 'profond',
            'defense': 'défense',
            'degree': 'degré',
            'democratic': 'démocratique',
            'describe': 'décrire',
            'design': 'design',
            'despite': 'malgré',
            'detail': 'détail',
            'determine': 'déterminer',
            'develop': 'développer',
            'development': 'développement',
            'die': 'mourir',
            'difference': 'différence',
            'different': 'différent',
            'difficult': 'difficile',
            'dinner': 'dîner',
            'direction': 'direction',
            'director': 'directeur',
            'discover': 'découvrir',
            'discuss': 'discuter',
            'discussion': 'discussion',
            'disease': 'maladie',
            'do': 'faire',
            'doctor': 'docteur',
            'dog': 'chien',
            'door': 'porte',
            'down': 'vers le bas',
            'draw': 'dessiner',
            'dream': 'rêve',
            'drive': 'conduire',
            'drop': 'tomber',
            'drug': 'drogue',
            'during': 'pendant',
            'each': 'chaque',
            'early': 'tôt',
            'east': 'est',
            'easy': 'facile',
            'eat': 'manger',
            'economic': 'économique',
            'economy': 'économie',
            'edge': 'bord',
            'education': 'éducation',
            'effect': 'effet',
            'effective': 'efficace',
            'effort': 'effort',
            'eight': 'huit',
            'either': 'soit',
            'election': 'élection',
            'else': 'autre',
            'employee': 'employé',
            'end': 'fin',
            'energy': 'énergie',
            'enjoy': 'apprécier',
            'enough': 'assez',
            'enter': 'entrer',
            'entire': 'entier',
            'environment': 'environnement',
            'especially': 'surtout',
            'establish': 'établir',
            'even': 'même',
            'evening': 'soir',
            'event': 'événement',
            'ever': 'jamais',
            'every': 'chaque',
            'everybody': 'tout le monde',
            'everyone': 'tout le monde',
            'everything': 'tout',
            'evidence': 'preuve',
            'exactly': 'exactement',
            'example': 'exemple',
            'executive': 'exécutif',
            'exist': 'exister',
            'expect': 'attendre',
            'experience': 'expérience',
            'expert': 'expert',
            'explain': 'expliquer',
            'eye': 'œil',
            'face': 'visage',
            'fact': 'fait',
            'factor': 'facteur',
            'fail': 'échouer',
            'fall': 'tomber',
            'family': 'famille',
            'far': 'loin',
            'fast': 'rapide',
            'father': 'père',
            'fear': 'peur',
            'federal': 'fédéral',
            'feel': 'sentir',
            'feeling': 'sentiment',
            'few': 'peu',
            'field': 'champ',
            'fight': 'combattre',
            'figure': 'figure',
            'fill': 'remplir',
            'film': 'film',
            'final': 'final',
            'finally': 'finalement',
            'financial': 'financier',
            'find': 'trouver',
            'fine': 'bien',
            'finger': 'doigt',
            'finish': 'finir',
            'fire': 'feu',
            'firm': 'ferme',
            'first': 'premier',
            'fish': 'poisson',
            'five': 'cinq',
            'floor': 'sol',
            'fly': 'voler',
            'focus': 'focus',
            'follow': 'suivre',
            'food': 'nourriture',
            'foot': 'pied',
            'for': 'pour',
            'force': 'force',
            'foreign': 'étranger',
            'forget': 'oublier',
            'form': 'forme',
            'former': 'ancien',
            'forward': 'en avant',
            'four': 'quatre',
            'free': 'libre',
            'friend': 'ami',
            'from': 'de',
            'front': 'devant',
            'full': 'plein',
            'fund': 'fonds',
            'future': 'futur',
            'game': 'jeu',
            'garden': 'jardin',
            'gas': 'gaz',
            'general': 'général',
            'generation': 'génération',
            'get': 'obtenir',
            'girl': 'fille',
            'give': 'donner',
            'glass': 'verre',
            'go': 'aller',
            'goal': 'objectif',
            'god': 'dieu',
            'good': 'bon',
            'government': 'gouvernement',
            'great': 'grand',
            'green': 'vert',
            'ground': 'sol',
            'group': 'groupe',
            'grow': 'grandir',
            'growth': 'croissance',
            'guess': 'deviner',
            'gun': 'arme',
            'guy': 'gars',
            'hair': 'cheveux',
            'half': 'moitié',
            'hand': 'main',
            'hang': 'accrocher',
            'happen': 'arriver',
            'happy': 'heureux',
            'hard': 'dur',
            'have': 'avoir',
            'he': 'il',
            'head': 'tête',
            'health': 'santé',
            'hear': 'entendre',
            'heart': 'cœur',
            'heat': 'chaleur',
            'heavy': 'lourd',
            'help': 'aide',
            'her': 'elle',
            'here': 'ici',
            'herself': 'elle-même',
            'high': 'haut',
            'him': 'lui',
            'himself': 'lui-même',
            'his': 'son',
            'history': 'histoire',
            'hit': 'frapper',
            'hold': 'tenir',
            'home': 'maison',
            'hope': 'espoir',
            'hospital': 'hôpital',
            'hot': 'chaud',
            'hotel': 'hôtel',
            'hour': 'heure',
            'house': 'maison',
            'how': 'comment',
            'however': 'cependant',
            'huge': 'énorme',
            'human': 'humain',
            'hundred': 'cent',
            'husband': 'mari',
            'i': 'je',
            'idea': 'idée',
            'identify': 'identifier',
            'if': 'si',
            'image': 'image',
            'imagine': 'imaginer',
            'impact': 'impact',
            'important': 'important',
            'improve': 'améliorer',
            'in': 'dans',
            'include': 'inclure',
            'including': 'y compris',
            'increase': 'augmenter',
            'indeed': 'en effet',
            'indicate': 'indiquer',
            'individual': 'individuel',
            'industry': 'industrie',
            'information': 'information',
            'inside': 'à l\'intérieur',
            'instead': 'au lieu de',
            'institution': 'institution',
            'interest': 'intérêt',
            'interesting': 'intéressant',
            'international': 'international',
            'interview': 'entretien',
            'into': 'dans',
            'investment': 'investissement',
            'involve': 'impliquer',
            'issue': 'problème',
            'it': 'il/elle',
            'item': 'article',
            'its': 'son',
            'itself': 'lui-même',
            'job': 'travail',
            'join': 'rejoindre',
            'just': 'juste',
            'keep': 'garder',
            'key': 'clé',
            'kid': 'enfant',
            'kill': 'tuer',
            'kind': 'gentil/type',
            'kitchen': 'cuisine',
            'know': 'savoir',
            'knowledge': 'connaissance',
            'land': 'terre',
            'language': 'langue',
            'large': 'grand',
            'last': 'dernier',
            'late': 'tard',
            'later': 'plus tard',
            'laugh': 'rire',
            'law': 'loi',
            'lawyer': 'avocat',
            'lay': 'poser',
            'lead': 'mener',
            'leader': 'leader',
            'learn': 'apprendre',
            'least': 'au moins',
            'leave': 'partir',
            'left': 'gauche',
            'leg': 'jambe',
            'legal': 'légal',
            'less': 'moins',
            'let': 'laisser',
            'letter': 'lettre',
            'level': 'niveau',
            'lie': 'mentir',
            'life': 'vie',
            'light': 'lumière',
            'like': 'aimer',
            'likely': 'probable',
            'line': 'ligne',
            'list': 'liste',
            'listen': 'écouter',
            'little': 'petit',
            'live': 'vivre',
            'local': 'local',
            'long': 'long',
            'look': 'regarder',
            'lose': 'perdre',
            'loss': 'perte',
            'lot': 'beaucoup',
            'love': 'amour',
            'low': 'bas',
            'machine': 'machine',
            'magazine': 'magazine',
            'main': 'principal',
            'maintain': 'maintenir',
            'major': 'majeur',
            'make': 'faire',
            'man': 'homme',
            'manage': 'gérer',
            'management': 'gestion',
            'manager': 'manager',
            'many': 'beaucoup',
            'market': 'marché',
            'marriage': 'mariage',
            'material': 'matériel',
            'matter': 'question',
            'may': 'peut',
            'maybe': 'peut-être',
            'me': 'moi',
            'mean': 'signifier',
            'measure': 'mesure',
            'media': 'médias',
            'medical': 'médical',
            'meet': 'rencontrer',
            'meeting': 'réunion',
            'member': 'membre',
            'memory': 'mémoire',
            'mention': 'mentionner',
            'message': 'message',
            'method': 'méthode',
            'middle': 'milieu',
            'might': 'pourrait',
            'military': 'militaire',
            'million': 'million',
            'mind': 'esprit',
            'minute': 'minute',
            'miss': 'rater',
            'mission': 'mission',
            'model': 'modèle',
            'modern': 'moderne',
            'moment': 'moment',
            'money': 'argent',
            'month': 'mois',
            'more': 'plus',
            'morning': 'matin',
            'most': 'la plupart',
            'mother': 'mère',
            'mouth': 'bouche',
            'move': 'bouger',
            'movement': 'mouvement',
            'movie': 'film',
            'mr': 'monsieur',
            'mrs': 'madame',
            'much': 'beaucoup',
            'music': 'musique',
            'must': 'devoir',
            'my': 'mon',
            'myself': 'moi-même',
            'name': 'nom',
            'nation': 'nation',
            'national': 'national',
            'natural': 'naturel',
            'nature': 'nature',
            'near': 'près',
            'nearly': 'presque',
            'necessary': 'nécessaire',
            'need': 'besoin',
            'network': 'réseau',
            'never': 'jamais',
            'new': 'nouveau',
            'news': 'nouvelles',
            'newspaper': 'journal',
            'next': 'suivant',
            'nice': 'gentil',
            'night': 'nuit',
            'no': 'non',
            'none': 'aucun',
            'nor': 'ni',
            'north': 'nord',
            'not': 'pas',
            'note': 'note',
            'nothing': 'rien',
            'notice': 'remarquer',
            'now': 'maintenant',
            'number': 'numéro',
            'occur': 'arriver',
            'of': 'de',
            'off': 'éteint',
            'offer': 'offre',
            'office': 'bureau',
            'officer': 'officier',
            'official': 'officiel',
            'often': 'souvent',
            'oh': 'oh',
            'oil': 'huile',
            'ok': 'd\'accord',
            'old': 'vieux',
            'on': 'sur',
            'once': 'une fois',
            'one': 'un',
            'only': 'seulement',
            'onto': 'sur',
            'open': 'ouvrir',
            'operation': 'opération',
            'opportunity': 'opportunité',
            'option': 'option',
            'or': 'ou',
            'order': 'ordre',
            'organization': 'organisation',
            'other': 'autre',
            'others': 'autres',
            'our': 'notre',
            'out': 'dehors',
            'outside': 'dehors',
            'over': 'au-dessus',
            'own': 'propre',
            'owner': 'propriétaire',
            'page': 'page',
            'pain': 'douleur',
            'painting': 'peinture',
            'paper': 'papier',
            'parent': 'parent',
            'part': 'partie',
            'participant': 'participant',
            'particular': 'particulier',
            'particularly': 'particulièrement',
            'partner': 'partenaire',
            'party': 'fête',
            'pass': 'passer',
            'past': 'passé',
            'patient': 'patient',
            'pattern': 'modèle',
            'pay': 'payer',
            'peace': 'paix',
            'people': 'gens',
            'per': 'par',
            'perform': 'performer',
            'performance': 'performance',
            'perhaps': 'peut-être',
            'period': 'période',
            'person': 'personne',
            'personal': 'personnel',
            'phone': 'téléphone',
            'physical': 'physique',
            'pick': 'choisir',
            'picture': 'image',
            'piece': 'morceau',
            'place': 'lieu',
            'plan': 'plan',
            'plant': 'plante',
            'play': 'jouer',
            'player': 'joueur',
            'pm': 'après-midi',
            'point': 'point',
            'police': 'police',
            'policy': 'politique',
            'political': 'politique',
            'politics': 'politique',
            'poor': 'pauvre',
            'popular': 'populaire',
            'population': 'population',
            'position': 'position',
            'positive': 'positif',
            'possible': 'possible',
            'power': 'pouvoir',
            'practice': 'pratique',
            'prepare': 'préparer',
            'present': 'présent',
            'president': 'président',
            'pressure': 'pression',
            'pretty': 'joli',
            'prevent': 'prévenir',
            'price': 'prix',
            'private': 'privé',
            'probably': 'probablement',
            'problem': 'problème',
            'process': 'processus',
            'produce': 'produire',
            'product': 'produit',
            'production': 'production',
            'professional': 'professionnel',
            'professor': 'professeur',
            'program': 'programme',
            'project': 'projet',
            'property': 'propriété',
            'protect': 'protéger',
            'prove': 'prouver',
            'provide': 'fournir',
            'public': 'public',
            'pull': 'tirer',
            'purpose': 'but',
            'push': 'pousser',
            'put': 'mettre',
            'quality': 'qualité',
            'question': 'question',
            'quickly': 'rapidement',
            'quite': 'assez',
            'race': 'course',
            'radio': 'radio',
            'raise': 'lever',
            'range': 'gamme',
            'rate': 'taux',
            'rather': 'plutôt',
            'rating': 'évaluation',
            'reach': 'atteindre',
            'read': 'lire',
            'ready': 'prêt',
            'real': 'réel',
            'reality': 'réalité',
            'realize': 'réaliser',
            'really': 'vraiment',
            'reason': 'raison',
            'receive': 'recevoir',
            'recent': 'récent',
            'recently': 'récemment',
            'recognize': 'reconnaître',
            'record': 'enregistrement',
            'red': 'rouge',
            'reduce': 'réduire',
            'reflect': 'refléter',
            'region': 'région',
            'relate': 'relier',
            'relationship': 'relation',
            'religious': 'religieux',
            'remain': 'rester',
            'remember': 'se souvenir',
            'remove': 'enlever',
            'report': 'rapport',
            'represent': 'représenter',
            'republican': 'républicain',
            'require': 'exiger',
            'research': 'recherche',
            'resource': 'ressource',
            'respond': 'répondre',
            'response': 'réponse',
            'responsibility': 'responsabilité',
            'rest': 'repos',
            'result': 'résultat',
            'return': 'retourner',
            'reveal': 'révéler',
            'rich': 'riche',
            'right': 'droite',
            'rise': 'monter',
            'risk': 'risque',
            'road': 'route',
            'rock': 'rocher',
            'role': 'rôle',
            'room': 'chambre',
            'rule': 'règle',
            'run': 'courir',
            'safe': 'sûr',
            'same': 'même',
            'save': 'sauver',
            'say': 'dire',
            'scene': 'scène',
            'school': 'école',
            'science': 'science',
            'scientist': 'scientifique',
            'score': 'score',
            'sea': 'mer',
            'season': 'saison',
            'seat': 'siège',
            'second': 'second',
            'section': 'section',
            'security': 'sécurité',
            'see': 'voir',
            'seek': 'chercher',
            'seem': 'sembler',
            'sell': 'vendre',
            'send': 'envoyer',
            'senior': 'senior',
            'sense': 'sens',
            'series': 'série',
            'serious': 'sérieux',
            'serve': 'servir',
            'service': 'service',
            'set': 'ensemble',
            'seven': 'sept',
            'several': 'plusieurs',
            'sex': 'sexe',
            'sexual': 'sexuel',
            'shake': 'secouer',
            'share': 'partager',
            'she': 'elle',
            'shoot': 'tirer',
            'short': 'court',
            'shot': 'coup',
            'should': 'devrait',
            'show': 'montrer',
            'side': 'côté',
            'sign': 'signe',
            'significant': 'significatif',
            'similar': 'similaire',
            'simple': 'simple',
            'simply': 'simplement',
            'since': 'depuis',
            'sing': 'chanter',
            'single': 'célibataire',
            'sister': 'sœur',
            'sit': 's\'asseoir',
            'site': 'site',
            'situation': 'situation',
            'six': 'six',
            'size': 'taille',
            'skill': 'compétence',
            'skin': 'peau',
            'small': 'petit',
            'smile': 'sourire',
            'so': 'donc',
            'social': 'social',
            'society': 'société',
            'soldier': 'soldat',
            'some': 'quelques',
            'somebody': 'quelqu\'un',
            'someone': 'quelqu\'un',
            'something': 'quelque chose',
            'sometimes': 'parfois',
            'son': 'fils',
            'song': 'chanson',
            'soon': 'bientôt',
            'sort': 'sorte',
            'sound': 'son',
            'source': 'source',
            'south': 'sud',
            'southern': 'du sud',
            'space': 'espace',
            'speak': 'parler',
            'special': 'spécial',
            'specific': 'spécifique',
            'speech': 'discours',
            'spend': 'dépenser',
            'sport': 'sport',
            'spring': 'printemps',
            'staff': 'personnel',
            'stage': 'étape',
            'stand': 'se tenir debout',
            'standard': 'standard',
            'star': 'étoile',
            'start': 'commencer',
            'state': 'état',
            'statement': 'déclaration',
            'station': 'station',
            'stay': 'rester',
            'step': 'étape',
            'still': 'encore',
            'stock': 'stock',
            'stop': 'arrêter',
            'store': 'magasin',
            'story': 'histoire',
            'strategy': 'stratégie',
            'street': 'rue',
            'strong': 'fort',
            'structure': 'structure',
            'student': 'étudiant',
            'study': 'étude',
            'stuff': 'trucs',
            'style': 'style',
            'subject': 'sujet',
            'success': 'succès',
            'successful': 'réussi',
            'such': 'tel',
            'suddenly': 'soudainement',
            'suffer': 'souffrir',
            'suggest': 'suggérer',
            'summer': 'été',
            'support': 'soutien',
            'sure': 'sûr',
            'surface': 'surface',
            'system': 'système',
            'table': 'table',
            'take': 'prendre',
            'talk': 'parler',
            'task': 'tâche',
            'tax': 'taxe',
            'teach': 'enseigner',
            'teacher': 'professeur',
            'team': 'équipe',
            'technology': 'technologie',
            'television': 'télévision',
            'tell': 'dire',
            'ten': 'dix',
            'tend': 'tendre',
            'term': 'terme',
            'test': 'test',
            'than': 'que',
            'thank': 'remercier',
            'that': 'que',
            'the': 'le/la',
            'their': 'leur',
            'them': 'eux',
            'themselves': 'eux-mêmes',
            'then': 'alors',
            'theory': 'théorie',
            'there': 'là',
            'these': 'ces',
            'they': 'ils',
            'thing': 'chose',
            'think': 'penser',
            'third': 'troisième',
            'this': 'ce',
            'those': 'ceux',
            'though': 'bien que',
            'thought': 'pensée',
            'thousand': 'mille',
            'threat': 'menace',
            'three': 'trois',
            'through': 'à travers',
            'throughout': 'tout au long',
            'throw': 'jeter',
            'thus': 'ainsi',
            'time': 'temps',
            'to': 'à',
            'today': 'aujourd\'hui',
            'together': 'ensemble',
            'tonight': 'ce soir',
            'too': 'aussi',
            'top': 'haut',
            'total': 'total',
            'tough': 'dur',
            'toward': 'vers',
            'town': 'ville',
            'trade': 'commerce',
            'traditional': 'traditionnel',
            'training': 'formation',
            'travel': 'voyage',
            'treat': 'traiter',
            'treatment': 'traitement',
            'tree': 'arbre',
            'trial': 'procès',
            'trip': 'voyage',
            'trouble': 'problème',
            'true': 'vrai',
            'truth': 'vérité',
            'try': 'essayer',
            'turn': 'tourner',
            'tv': 'télé',
            'two': 'deux',
            'type': 'type',
            'under': 'sous',
            'understand': 'comprendre',
            'unit': 'unité',
            'until': 'jusqu\'à',
            'up': 'en haut',
            'upon': 'sur',
            'us': 'nous',
            'use': 'utiliser',
            'used': 'utilisé',
            'user': 'utilisateur',
            'usually': 'habituellement',
            'value': 'valeur',
            'various': 'divers',
            'very': 'très',
            'victim': 'victime',
            'view': 'vue',
            'violence': 'violence',
            'visit': 'visiter',
            'voice': 'voix',
            'vote': 'vote',
            'wait': 'attendre',
            'walk': 'marcher',
            'wall': 'mur',
            'want': 'vouloir',
            'war': 'guerre',
            'watch': 'regarder',
            'water': 'eau',
            'way': 'chemin',
            'we': 'nous',
            'weapon': 'arme',
            'wear': 'porter',
            'week': 'semaine',
            'weight': 'poids',
            'well': 'bien',
            'west': 'ouest',
            'western': 'occidental',
            'what': 'quoi',
            'whatever': 'quoi que',
            'when': 'quand',
            'where': 'où',
            'whether': 'si',
            'which': 'lequel',
            'while': 'pendant',
            'white': 'blanc',
            'who': 'qui',
            'whole': 'entier',
            'whom': 'qui',
            'whose': 'dont',
            'why': 'pourquoi',
            'wide': 'large',
            'wife': 'épouse',
            'will': 'volonté',
            'win': 'gagner',
            'wind': 'vent',
            'window': 'fenêtre',
            'wish': 'souhait',
            'with': 'avec',
            'within': 'dans',
            'without': 'sans',
            'woman': 'femme',
            'wonder': 'se demander',
            'word': 'mot',
            'work': 'travail',
            'worker': 'travailleur',
            'world': 'monde',
            'worry': 's\'inquiéter',
            'would': 'voudrait',
            'write': 'écrire',
            'writer': 'écrivain',
            'wrong': 'faux',
            'yard': 'cour',
            'yeah': 'ouais',
            'year': 'année',
            'yes': 'oui',
            'yet': 'encore',
            'you': 'vous',
            'young': 'jeune',
            'your': 'votre',
            'yourself': 'vous-même'
        };

        for (const word of words) {
            const cleanWord = word.trim().toLowerCase();
            if (cleanWord.length === 0) continue;

            try {
                // Utiliser la traduction du dictionnaire ou une traduction générique
                const translation = basicTranslations[cleanWord] || `[${cleanWord}]`;

                // Déterminer la difficulté basée sur la longueur et la fréquence
                let difficulty = 'beginner';
                if (cleanWord.length > 8 || !basicTranslations[cleanWord]) {
                    difficulty = 'advanced';
                } else if (cleanWord.length > 5) {
                    difficulty = 'intermediate';
                }

                this.db.insertWord({
                    word: cleanWord,
                    translation: translation,
                    pronunciation: null,
                    partOfSpeech: null,
                    definition: null,
                    example: null,
                    exampleTranslation: null,
                    difficulty: difficulty,
                    category: 'general'
                });
                imported++;
            } catch (error) {
                if (error.code === 'SQLITE_CONSTRAINT_UNIQUE') {
                    skipped++;
                } else {
                    console.error(`❌ Erreur pour le mot "${cleanWord}":`, error.message);
                }
            }
        }

        console.log(`✅ Migration des 3000 mots terminée: ${imported} mots importés, ${skipped} mots ignorés (doublons)`);
        return { imported, skipped };
    }

    // Migration complète
    async migrateAll() {
        console.log('🚀 Démarrage de la migration complète...');

        // Réinitialiser la base
        this.db.reset();

        // Migrer les mots détaillés d'abord
        const wordsResult = await this.migrateWordsData();

        // Puis migrer les 3000 mots
        const thousandWordsResult = await this.migrate3000Words();

        // Statistiques finales
        const totalWords = this.db.getTotalWordsCount();
        const categories = this.db.getCategories();

        console.log('\n📊 Statistiques de migration:');
        console.log(`   Total de mots en base: ${totalWords}`);
        console.log(`   Mots détaillés importés: ${wordsResult.imported}`);
        console.log(`   Mots de la liste 3000 importés: ${thousandWordsResult.imported}`);
        console.log(`   Catégories disponibles: ${categories.length}`);
        console.log(`   Catégories: ${categories.join(', ')}`);

        return {
            totalWords,
            detailedWords: wordsResult.imported,
            basicWords: thousandWordsResult.imported,
            categories: categories.length
        };
    }
}

export default DataMigration;
